### PR TITLE
Add basic like() support

### PR DESCRIPTION
**Pull request by DavidePastore**
I have different things to add to this PR:
- [ ] handle "%" before string;
- [ ] handle "%" after string.

Feedbacks are accepted.

### CODE REVIEW

**Comment by DavidePastore** [comment]
Hi @Greg0 , I was still working on this. :smile_cat:

**Comment by FalkoJoseph** [comment]
:+1:

**Comment by Greg0** [comment]
So should I revert this?

**Comment by DavidePastore** [comment]
Yes, if it's simple. I could improve `like` a lot.

**Comment by Greg0** [comment]
Done

**Comment by DavidePastore** [comment]
Check #14 .

**Pull request merged**
