### PR TITLE
Update Relation.php: hasMany relation is working now

### PR DESCRIPTION
**Pull request by dmitry-volkoff**

### CODE REVIEW

**Comment by Greg0** [comment]
Missing unit tests

**Comment by anant-svc** [comment]
@dmitry-volkoff create a unit test for your use case

**Comment by anant-svc** [comment]
@dmitry-volkoff Why you created two PRs for same fix. You can push the tests in **dmitry-volkoff:dmitry-volkoff-patch-1** branch.

**Comment by anant-svc** [comment]
All changes are in PR - https://github.com/Lazer-Database/Lazer-Database/pull/79

**Pull request closed without merging**
