### PR TITLE
Add basic 'like' support

### PR DESCRIPTION
**Pull request by DavidePastore**
This is a better implementation. Check it. :smile_cat:

### CODE REVIEW

**Comment by Greg0** [comment]
Keep it simple, don't make it an overkill :)
Look here, i think RegEx i good option: http://stackoverflow.com/questions/562823/php-way-to-execute-sql-like-matching-without-a-database-query
and preg_grep... what a wonderful function :)

**Comment by Greg0** [comment]
Checkout my implementation

**Comment by DavidePastore** [comment]
It's ok for me. :+1:  What I noticed is that it is case sensitive. It could be fine if we could have an option to say if we want database (or query) to be so.

**Comment by Greg0** [comment]
Yes, whole where() method is case sensitive and I though about some changes here. 
Maybe soon :smile:

**Pull request closed without merging**
